---
deployment:
  tasks:
    -export DEPLOYPATH=/home/u5775975/public_html/surat
    -/bin/cp -R * $DEPLOYPATH
    -/bin/cp ./public/js/*.js $DEPLOYPATH/js
    -/bin/cp ./public/css/*.css $DEPLOYPATH/css
